### ISSUE TITLE
Code chức năng có STT 16 (confirm page)

### ISSUE THREAD

**Issue by PikarryPham** [PikarryPham/vnvcwebsite#10]
- Có sử dụng MongoDB + Redis làm cache
- Trước mắt cần code thành công chạy bằng MongoDB, sau đó mới áp dụng thêm Redis làm cache
- Cần hoàn thành xong sớm để người khác bắt đầu code

**Comment by PikarryPham** [comment]
Đã chỉnh sửa lại task, Ân chỉ code chức năng cho trang 16 thôi

**Comment by hntruc** [comment]
Gud job everyone !!!
